import { Router } from 'express';
import { authenticate } from '../../middlewares/auth.middleware';
import { requireTenant } from '../../middlewares/tenant.middleware';
import { AuthRequest } from '../../types';
import { sendSuccess } from '../../utils/response';
import { Permission } from './permission.model';
import mongoose from 'mongoose';

const router = Router();

router.use(authenticate, requireTenant);

/**
 * GET /permissions
 * Returns all permissions available to this tenant:
 * - System-level permissions (tenantId: null)
 * - Tenant-specific dynamic permissions (generated by connector sync)
 *
 * Optional query params:
 *   ?module=connector      — filter by module (prefix match)
 *   ?scope=dynamic         — filter by scope: platform | connector | dynamic
 *   ?group=1               — group by module in response
 */
router.get('/', async (req: AuthRequest, res, next) => {
  try {
    const tenantId = req.user!.tenantId;
    const { module: moduleFilter, scope, group } = req.query as {
      module?: string;
      scope?: string;
      group?: string;
    };

    const filter: Record<string, unknown> = {
      $or: [
        { tenantId: null },
        { tenantId: new mongoose.Types.ObjectId(tenantId) },
      ],
    };

    if (moduleFilter) filter.module = moduleFilter;
    if (scope) filter.scope = scope;

    const permissions = await Permission
      .find(filter, 'key module resource action label scope isSystem connectorId tenantId')
      .sort({ module: 1, resource: 1, action: 1 })
      .lean();

    if (group === '1') {
      const grouped: Record<string, typeof permissions> = {};
      for (const p of permissions) {
        if (!grouped[p.module]) grouped[p.module] = [];
        grouped[p.module].push(p);
      }
      return sendSuccess(res, grouped);
    }

    return sendSuccess(res, permissions);
  } catch (err) {
    next(err);
  }
});

export default router;
